Laptop/Laptop/Controllers/newController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Laptop.Models;


namespace Laptop.Controllers
{
    public class newController : Controller
    {
        laptopDataContext db = new laptopDataContext();
        // GET: new
        public ActionResult Index(int? page)
        {
            if (Session["admin"] == null)
            {
                return RedirectToAction("Index", "loginAdmin");
            }
            var tin = from b in db.News
                        select b;
            ViewBag.tin = tin;
            return View(tin.ToPagedList(page ?? 1, 5));
        }
        /*[HttpPost]
        public ActionResult Index(int? page, FormCollection a)
        {
            string title = Request["key"];
            var tin = from b in db.News
                        where b.Title.Contains(title)
                        select b;
            return View(tin.ToPagedList(page ?? 1, 5));
        }*/
        public ActionResult Create()
        {
            if (Session["admin"] == null)
            {
                return RedirectToAction("Index", "loginAdmin");
            }
            var tin = (from b in db.News
                         orderby b.ID descending
                         select b).Take(3);
            return View(tin);
        }
        [HttpPost]
        public ActionResult Create(New tin)
        {
            New test = db.News.Where(p => p.Title == Request["Title"]).FirstOrDefault();
            ViewBag.date = DateTime.Now;
            if (test != null)
            {
                ViewBag.test = "Tiêu đề " + Request["Title"] + " đã tồn tại!";
            }
            else
            {
                tin.Title = Request["Title"];                
                tin.Content = Request["Content"];
                tin.Image = Request["Anh"];
                tin.created_at = ViewBag.date;
                db.News.InsertOnSubmit(tin);
                db.SubmitChanges();
            }

            return this.Create();
        }
        public ActionResult Edit(int id)
        {
            var tin = db.News.First(b => b.ID == id);
            return View(tin);
        }
        [HttpPost]
        public ActionResult Edit(int id, New tin)
        {
            /*var filename = Request["anh"];*/
            ViewBag.date = DateTime.Now;
            tin = db.News.Where(b => b.ID == id).SingleOrDefault();
            tin.Title = Request["Title"];
            tin.Content = Request["Content"];
            tin.Image = Request["Anh"];
            tin.updated_at = ViewBag.date;
            /*
            tin.Image = "/Content/tin/Image/" + GetFileName(file.FileName);*/
            UpdateModel(tin);
            db.SubmitChanges();
            return RedirectToAction("Index");

            return this.Edit(id);
        }
        public ActionResult Edit_cre(int id)
        {
            var tin = db.News.First(b => b.ID == id);
            return View(tin);
        }
        [HttpPost]
        public ActionResult Edit_cre(int id, New tin)
        {
            /*var filename = Request["anh"];*/
            ViewBag.date = DateTime.Now;
            tin = db.News.Where(b => b.ID == id).SingleOrDefault();
            tin.Title = Request["Title"];
            tin.Content = Request["Content"];
            tin.Image = Request["Anh"];
            tin.updated_at = ViewBag.date;
            /*
            tin.Image = "/Content/tin/Image/" + GetFileName(file.FileName);*/
            UpdateModel(tin);
            db.SubmitChanges();
            return RedirectToAction("Create");

            return this.Edit(id);
        }
        public ActionResult Delete(int id)
        {
            var tin = db.News.Where(b => b.ID == id).SingleOrDefault();
            db.News.DeleteOnSubmit(tin);
            db.SubmitChanges();
            return RedirectToAction("Index");
        }
        public ActionResult Delete_cre(int id)
        {
            var tin = db.News.Where(b => b.ID == id).SingleOrDefault();
            db.News.DeleteOnSubmit(tin);
            db.SubmitChanges();
            return RedirectToAction("Create");
        }
    }
}

Laptop/Laptop/Views/New/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Admin.cshtml";
}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/test/Index">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Form thêm tin</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<div class="card-body pad">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title" style="text-align:center; width:100%">Form thêm tin</h3>
                </div>
                <form method="post" action="/new/Create">
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                                <tr align="center">
                                    <th>Tiêu đề</th>
                                    <th>Nội dung</th>
                                    <th>Avatar</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>

                                <tr class="odd gradeX" align="center">
                                    <td>
                                        <input type="text" class="form-control" placeholder="Điền tiêu đề" name="Title">
                                    </td>
                                    <td>
                                        <input type="text" class="form-control" placeholder="Điền nội dung" name="Content">
                                    </td>
                                    <td>
                                        @*<img src="@Model.Image" width="100" height="100" />*@
                                        <input type="text" class="form-control" placeholder="Điền link ảnh" name="Anh">
                                    </td>
                                    <td>
                                        <button type="submit" class="btn btn-primary">Thêm</button>
                                    </td>
                                </tr>

                            </tbody>
                        </table>
                    </div>
                </form>
                <h3 style="text-align:center; color:red">@ViewBag.test</h3>
            </div>
            <!-- /.card -->
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header" style="background-color:sandybrown">
                    <h3 class="card-title" style="text-align:center; width:100%">Thông tin 3 tin được thêm gần nhất</h3>
                </div>
                <div class="card-body">

                    <table id="example2" class="table table-bordered table-hover">
                        <thead>
                            <tr align="center">
                                <th>Tiêu đề</th>
                                <th>Nội dung</th>
                                <th>Avatar</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr class="odd gradeX" align="center">
                                <td>@item.Title</td>
                                <td>@item.Content</td>
                                <td><img src="@item.Image" width="100" height="100" /></td>
                                <td>
                                    @Html.ActionLink("Sửa", "Edit_cre", new { id = item.ID })
                                    @*<i class="fa fa-trash-o" fa-fw></i>@Html.ActionLink("Sửa", "Edit_cre", new { id = item.ID })
                                    <i class="fa fa-pencil fa-fw"></i>@Html.ActionLink("Xóa", "Delete_cre", new { id = item.ID })*@
                                </td>
                            </tr>

                            }
                        </tbody>

                    </table>


                </div>
            </div>
        </div>
    </div>
</div>

Laptop/Laptop/Views/New/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/test/Index">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Form sửa tin</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<div class="card-body pad">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title" style="text-align:center; width:100%">Form sửa tin</h3>
                </div>
                <form role="form" method="post" action="/new/Edit/@Model.ID"
                      enctype="multipart/form-data">
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                                <tr align="center">
                                    <th>ID</th>
                                    <th>Tiêu đề</th>
                                    <th>Nội dung</th>
                                    <th>Avatar</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>

                                <tr class="odd gradeX" align="center">
                                    <td>
                                        @Model.ID
                                    </td>
                                    <td>
                                        <input type="text" class="form-control" placeholder="Điền tiêu đề"
                                               name="Title" value="@Model.Title">
                                    </td>
                                    <td>
                                        <input type="text" class="form-control" placeholder="Điền mô tả"
                                               name="Content" value="@Model.Content">
                                    </td>
                                    <td>
                                        <input required="" type="text" class="form-control" placeholder="Điền link ảnh"
                                               name="Anh" value="@Model.Image">
                                    </td>
                                    <td>

                                        <button type="submit" class="btn btn-primary">Sửa</button>
                                    </td>
                                </tr>

                            </tbody>
                        </table>
                    </div>
                </form>
            </div>
            <!-- /.card -->
        </div>
    </div>
</div>

Laptop/Laptop/Views/New/Edit_cre.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/test/Index">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Form sửa tin</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<div class="card-body pad">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title" style="text-align:center; width:100%">Form sửa tin</h3>
                </div>
                <form role="form" method="post" action="/new/Edit_cre/@Model.ID"
                      enctype="multipart/form-data">
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                                <tr align="center">
                                    <th>ID</th>
                                    <th>Tiêu đề</th>
                                    <th>Nội dung</th>
                                    <th>Avatar</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>

                                <tr class="odd gradeX" align="center">
                                    <td>
                                        @Model.ID
                                    </td>
                                    <td>
                                        <input type="text" class="form-control" placeholder="Điền tiêu đề"
                                               name="Title" value="@Model.Title">
                                    </td>
                                    <td>
                                        <input type="text" class="form-control" placeholder="Điền mô tả"
                                               name="Content" value="@Model.Content">
                                    </td>
                                    <td>
                                        <input required="" type="text" class="form-control" placeholder="Điền link ảnh"
                                               name="Anh" value="@Model.Image">
                                    </td>
                                    <td>

                                        <button type="submit" class="btn btn-primary">Sửa</button>
                                    </td>
                                </tr>

                            </tbody>
                        </table>
                    </div>
                </form>
            </div>
            <!-- /.card -->
        </div>
    </div>
</div>

Laptop/Laptop/Views/New/Index.cshtml
@*@model IPagedList<Laptop.Models.New>

@using PagedList.Mvc;
@using PagedList;*@
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Admin.cshtml";
}
<style>
</style>
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Tin tức</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/test/Index">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Tin tức</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

@*<form class="form-inline ml-3" method="post" action="/new/Index">
    <div class="container h-100">
        <div class="d-flex justify-content-center h-100">
            <div class="searchbar">
                <input class="search_input" type="text" name="key" placeholder="Tìm kiếm">
                <button type="submit" class="btn btn-primary" style="background-color:white; border-color:white; color:blue">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </div>
</form>
<br>*@

<!-- Main content -->
<section class="content">
    <div class="card-body pad">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title" style="text-align:center; width:100%">Bảng Tin tức</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example" class="table table-bordered table-hover">
                            <thead>
                                <tr align="center">
                                    <th>ID</th>
                                    <th>Tiêu đề</th>
                                    <th>Nội dung</th>
                                    <th>Avatar</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in ViewBag.tin)
                                {
                                    <tr class="odd gradeX" align="center">
                                        <td>@item.ID</td>
                                        <td>@item.Title</td>
                                        <td>@item.Content</td>
                                        <td><img src="@item.Image" width="70" height="70" /></td>
                                        <td>
                                            @Html.ActionLink("Sửa", "Edit", new { id = item.ID })
                                            @*<i class="fa fa-trash-o" fa-fw></i>@Html.ActionLink("Sửa", "Edit", new { id = item.ID })
                                            <i class="fa fa-pencil fa-fw"></i>@Html.ActionLink("Xóa", "Delete", new { id = item.ID })*@
                                        </td>
                                    </tr>
                                }
                            </tbody>
                            <tfoot>
                                <tr align="center">
                                    <th>ID</th>
                                    <th>Tiêu đề</th>
                                    <th>Nội dung</th>
                                    <th>Avatar</th>
                                    <th>Action</th>
                                </tr>
                            </tfoot>
                        </table>
                       @* <div style="margin-left: 50%;" class="paginate">
                            @Html.PagedListPager(Model, page => Url.Action("Index", "new", new { page }))
                        </div>*@

                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->

            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>
<!-- /.content -->