Laptop/Laptop/Controllers/billController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Laptop.Models;
using Laptop.Controllers;

namespace Laptop.Controllers
{
    public class billController : Controller
    {
        laptopDataContext db = new laptopDataContext();
        // GET: bill
        public ActionResult Index(int? page)
        {
            if(Session["admin"]==null)
            {
                return RedirectToAction("Index", "loginAdmin");
            }    
            var bill = from b in db.Bills
                       orderby b.Date_order descending
                        select b;
            ViewBag.bill = bill;
            return View(bill.ToPagedList(page ?? 1, 5));
        }/*
        [HttpPost]
        public ActionResult Index(int? page, FormCollection a)
        {
            DateTime date = Convert.ToDateTime( Request["key"]);
            var bill = from b in db.Bills
                        where b.Date_order==date
                        select b;
            return View(bill.ToPagedList(page ?? 1, 5));
        }*/
        public ActionResult Bill_Detail(int id)
        {
            ViewBag.bill_detail = (from bd in db.Bill_Details
                                  join b in db.Bills on bd.ID_Bill equals b.ID
                                  join cus in db.Customers on b.ID_Customer equals cus.ID
                                  join pro_co in db.Product_Colors on bd.ID_Product_Color equals pro_co.ID
                                  join pro in db.Products on pro_co.ID_Product equals pro.ID
                                  join bra in db.Brands on pro.ID_Brand equals bra.ID
                                  join co in db.Colorrs on pro_co.ID_Color equals co.ID
                                  where bd.ID_Bill == id
                                  select new Bill_Detaill
                                  {
                                      ID = bd.ID,
                                      ID_Bill= b.ID,
                                      Quantity = (int)bd.Quantity,
                                      Cus_Name=cus.Name,
                                      Cus_Email=cus.Email,
                                      Bill_Add = b.Address,
                                      Cus_Phone= b.Phone_Number,
                                      Cus_Gender=cus.Gender,
                                      Pro_Name=pro.Name,
                                      Pro_Brand=bra.Name,
                                      Pro_Price=(decimal)pro.Promotion_Price,
                                      Pro_Color= co.Color
                                  }).Distinct();
            ViewBag.Cus_Detail = (from bd in db.Bill_Details
                                   join b in db.Bills on bd.ID_Bill equals b.ID
                                   join cus in db.Customers on b.ID_Customer equals cus.ID
                                   /*join pro_co in db.Product_Colors on bd.ID_Product_Color equals pro_co.ID
                                   join pro in db.Products on pro_co.ID_Product equals pro.ID
                                   join bra in db.Brands on pro.ID_Brand equals bra.ID
                                   join co in db.Colorrs on pro_co.ID_Color equals co.ID*/
                                   where bd.ID_Bill == id
                                   select new Bill_Detaill
                                   {           
                                       ID_Bill= b.ID,
                                       Cus_Name = cus.Name,
                                       Cus_Email = cus.Email,
                                       Cus_Phone = b.Phone_Number,
                                       Bill_Add = b.Address,
                                       
                                   }).Distinct();
            return View();
        }
        public ActionResult Edit(int id)
        {
            var bill = db.Bills.First(b => b.ID == id);
            return View(bill);
        }
        [HttpPost]
        public ActionResult Edit(int id, Bill bill)
        {
            ViewBag.date = DateTime.Now;
            bill = db.Bills.Where(b => b.ID == id).SingleOrDefault();
            bill.Confirm = Request["confirm"];
            UpdateModel(bill);
            db.SubmitChanges();
            return RedirectToAction("Index");
        }
    }
}

Laptop/Laptop/Views/bill/Bill_Detail.cshtml
@*@model IPagedList<Laptop.Models.Bill_Detail>

    @using PagedList.Mvc;
    @using PagedList;*@
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Admin.cshtml";
}
<style>
</style>
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Chi tiết hóa đơn</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/test/Index">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Chi tiết hóa đơn</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

@*<form class="form-inline ml-3" method="post" action="/bill/Index">
        <div class="container h-100">
            <div class="d-flex justify-content-center h-100">
                <div class="searchbar">
                    <input class="search_input" type="text" name="key" placeholder="Tìm kiếm">
                    <button type="submit" class="btn btn-primary" style="background-color:white; border-color:white; color:blue">
                        <i class="fas fa-search"></i>
                    </button>
                </div>
            </div>
        </div>
    </form>
    <br>*@

<!-- Main content -->
@foreach (var item in ViewBag.Cus_Detail)
{
    <div class="row">
        <div class="col-1">
        </div>
        <div class="col-2">
            <b>Số hóa đơn:</b>
        </div>
        <div class="col-2">
            @item.ID_Bill
        </div>
    </div>
    <div class="row">
        <div class="col-1">
        </div>
        <div class="col-2">
            <b>Tên khách hàng:</b>
        </div>
        <div class="col-2">
            @item.Cus_Name
        </div>
    </div>
    <div class="row">
        <div class="col-1">
        </div>
        <div class="col-2">
            <b>Email:</b>
        </div>
        <div class="col-2">
            @item.Cus_Email
        </div>
    </div>
    <div class="row">
        <div class="col-1">
        </div>
        <div class="col-2">
            <b>Số điện thoại: </b>
        </div>
        <div class="col-2">
            <r>0</r>@item.Cus_Phone
        </div>
    </div>
    <div class="row">
        <div class="col-1">
        </div>
        <div class="col-2">
            <b>Địa chỉ nhận hàng:</b>
        </div>
        <div class="col-2">
            @item.Bill_Add
        </div>
    </div>
}

<section class="content">
    <div class="card-body pad">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title" style="text-align:center; width:100%">Bảng chi tiết</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                                <tr align="center">
                                    <th>Tên sản phẩm</th>
                                    <th>Màu sắc</th>
                                    <th>Tên hãng</th>
                                    <th>Số lượng</th>
                                    <th>Đơn giá</th>
                                    @*<th>Action</th>*@
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in ViewBag.bill_detail)
                                {
                                    <tr class="odd gradeX" align="center">
                                        <td>@item.Pro_Name</td>
                                        <td>@item.Pro_Color</td>
                                        <td>@item.Pro_Brand</td>
                                        <td>@item.Quantity</td>
                                        <td>@string.Format("{0:#,##0}",@item.Pro_Price)đ</td>
                                        @*<td>
                                                @Html.ActionLink("Chi tiết", "Bill_Detail", new { id = item.ID })
                                                <i class="fa fa-trash-o" fa-fw></i>@Html.ActionLink("Sửa", "Edit", new { id = item.ID })
                                                    <i class="fa fa-pencil fa-fw"></i>@Html.ActionLink("Xóa", "Delete", new { id = item.ID })
                                            </td>*@
                                    </tr>
                                }
                            </tbody>
                            <tfoot>
                                <tr align="center">
                                    <th>Tên sản phẩm</th>
                                    <th>Màu sắc</th>
                                    <th>Tên hãng</th>
                                    <th>Số lượng</th>
                                    <th>Đơn giá</th>
                                </tr>
                            </tfoot>
                        </table>
                        <div>
                            <br />
                            <div class="row" style="background-color:aqua">
                                <div style="text-align:right" class="col-6">$ Tổng tiền : </div>
                                <div class="col-6" style="text-align:left">
                                    @{
                                        decimal a = 0;
                                        decimal b = 0;
                                        foreach (var item in ViewBag.bill_detail)
                                        {
                                            a = a + item.Pro_Price * item.Quantity;
                                            
                                        }
                                        <p>@string.Format("{0:#,##0}",@a)đ</p>
                                    }
                                </div>
                            </div>
                        </div>
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->

            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>
<!-- /.content -->

Laptop/Laptop/Views/bill/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/test/Index">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Form cập nhật thông tin hóa đơn</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<div class="card-body pad">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title" style="text-align:center; width:100%">Form sửa thông tin hãng</h3>
                </div>
                <form role="form" method="post" action="/bill/Edit/@Model.ID"
                      enctype="multipart/form-data">
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                                <tr align="center">
                                    <th>ID</th>
                                    <th>ID khách hàng</th>
                                    <th>Ngày đặt hàng</th>
                                    <th>Địa chỉ nhận hàng</th>
                                    <th>Giao hàng</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>

                                <tr class="odd gradeX" align="center">
                                    <td>
                                        @Model.ID
                                    </td>
                                    <td>
                                        @Model.ID_Customer
                                    </td>
                                    <td>
                                        @Model.Date_order
                                    </td>
                                    <td>
                                        @Model.Address
                                    </td>
                                    <td>
                                        @if (Model.Confirm == "Đã nhận được hàng")
                                        {
                                            @Model.Confirm
                                        }
                                        else if(Model.Confirm == "Đã xác nhận")
                                        {
                                            <select name="confirm" style="width:250px;height:25px">
                                                <option value="Đang giao hàng">Đang giao hàng</option>
                                            </select>
                                        }
                                        else if(Model.Confirm == "Đang giao hàng")
                                        {
                                            <select name="confirm" style="width:250px;height:25px">
                                                <option value="Đã giao hàng">Đã giao hàng</option>
                                            </select>
                                        }
                                        else if (Model.Confirm == "Chờ xác nhận")
                                        {
                                            <select name="confirm" style="width:250px;height:25px">
                                                <option value="Đã xác nhận">Đã xác nhận</option>
                                                <option value="Đang giao hàng">Đang giao hàng</option>
                                            </select>
                                        }

                                    </td>

                                    <td>

                                        <button type="submit" class="btn btn-primary">Sửa</button>
                                    </td>
                                </tr>

                            </tbody>
                        </table>
                    </div>
                </form>
            </div>
            <!-- /.card -->
        </div>
    </div>
</div>

Laptop/Laptop/Views/bill/Index.cshtml
@*@model IPagedList<Laptop.Models.Bill>

    @using PagedList.Mvc;
    @using PagedList;*@
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Admin.cshtml";
}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Hóa đơn</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/test/Index">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Hóa đơn</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
@*
<form class="form-inline ml-3" method="post" action="/bill/Index">
    <div class="container h-100">
        <div class="d-flex justify-content-center h-100">
            <div class="searchbar">
                <input class="search_input" type="text" name="key" placeholder="Tìm kiếm">
                <button type="submit" class="btn btn-primary" style="background-color:white; border-color:white; color:blue">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </div>
</form>
<br>*@

<!-- Main content -->
<section class="content">
    <div class="card-body pad">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title" style="text-align:center; width:100%">Bảng hóa đơn</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example" class="table table-bordered table-hover">
                            <thead>
                                <tr align="center">
                                    <th>ID</th>
                                    <th>ID khách hàng</th>
                                    <th>Ngày đặt hàng</th>
                                    <th>Địa chỉ nhận hàng</th>
                                    <th>Giao hàng</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in @ViewBag.bill)
                                {
                                    <tr class="odd gradeX" align="center">
                                        <td>@item.ID</td>
                                        <td>@item.ID_Customer</td>
                                        <td>@item.Date_order</td>
                                        <td>@item.Address</td>
                                        <td>@item.Confirm</td>
                                        <td>
                                            @Html.ActionLink("Chi tiết", "Bill_Detail", new { id = item.ID })<br />
                                            @Html.ActionLink("Cập nhật", "Edit", new { id = item.ID })
                                        </td>
                                    </tr>
                                }
                            </tbody>
                            <tfoot>
                                <tr align="center">
                                    <th>ID</th>
                                    <th>ID khách hàng</th>
                                    <th>Ngày đặt hàng</th>
                                    <th>Địa chỉ nhận hàng</th>
                                    <th>Giao hàng</th>
                                    <th>Action</th>
                                </tr>
                            </tfoot>
                        </table>
                        @*<div style="margin-left: 50%;" class="paginate">
                            @Html.PagedListPager(Model, page => Url.Action("Index", "bill", new { page }))
                        </div>*@
                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->

            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>
<!-- /.content -->