Laptop/Laptop/Controllers/slideController.cs
using PagedList;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web;
using System.Web.Mvc;
using Laptop.Models;

namespace Laptop.Controllers
{
    public class slideController : Controller
    {
        // GET: slide
        laptopDataContext db = new laptopDataContext();
        
        public ActionResult Index(int? page)
        {
            if (Session["admin"] == null)
            {
                return RedirectToAction("Index", "loginAdmin");
            }
            var slide = from b in db.Slides
                        select b;
            ViewBag.slide = slide;
            return View(slide.ToPagedList(page ?? 1, 5));
        }/*
        [HttpPost]
        public ActionResult Index(int? page, FormCollection a)
        {

            string name = Request["key"];
            var slide = from b in db.Slides
                        where b.Title.Contains(name)
                        select b;
            return View(slide.ToPagedList(page ?? 1, 5));
        }*/
        public ActionResult Create()
        {
            if (Session["admin"] == null)
            {
                return RedirectToAction("Index", "loginAdmin");
            }
            var slide = (from b in db.Slides
                         orderby b.ID descending
                         select b).Take(3);
            return View(slide);
        }
        [HttpPost]
        public ActionResult Create(Slide slide)
        {
            Slide test = db.Slides.Where(p => p.Title == Request["Ten"]).FirstOrDefault();
            ViewBag.date = DateTime.Now;
            if (test != null)
            {
                ViewBag.test = "Tiêu đề đã tồn tại!";
            }
            else
            {
                slide.Title = Request["Ten"];
                slide.Action = Request["action"];
                slide.Content = Request["content"];
                slide.Discount = Convert.ToInt32(Request["discount"]);
                slide.Image = Request["Anh"];
                slide.created_at = ViewBag.date;
                db.Slides.InsertOnSubmit(slide);
                db.SubmitChanges();
            }

            return this.Create();
        }
        public ActionResult Edit(int id)
        {
            var slide = db.Slides.First(b => b.ID == id);
            return View(slide);
        }
        [HttpPost]
        public ActionResult Edit(int id, Slide slide)
        {
            /*var filename = Request["anh"];*/
            ViewBag.date = DateTime.Now;
            slide = db.Slides.Where(b => b.ID == id).SingleOrDefault();
            slide.Title = Request["Ten"];
            slide.Action = Request["action"];
            slide.Content = Request["content"];
            slide.Discount = Convert.ToInt32(Request["discount"]);
            slide.Image = Request["Anh"];
            slide.updated_at = ViewBag.date;
            /*
            slide.Image = "/Content/slide/Image/" + GetFileName(file.FileName);*/
            UpdateModel(slide);
            db.SubmitChanges();
            return RedirectToAction("Index");

            return this.Edit(id);
        }
        public ActionResult Delete(int id)
        {
            var slide = db.Slides.Where(b => b.ID == id).SingleOrDefault();
            db.Slides.DeleteOnSubmit(slide);
            db.SubmitChanges();
            return RedirectToAction("Index");
        }

        public ActionResult Edit_cre(int id)
        {
            var slide = db.Slides.First(b => b.ID == id);
            return View(slide);
        }
        [HttpPost]
        public ActionResult Edit_cre(int id, Slide slide)
        {
            /*var filename = Request["anh"];*/
            ViewBag.date = DateTime.Now;
            slide = db.Slides.Where(b => b.ID == id).SingleOrDefault();
            slide.Title = Request["Ten"];
            slide.Action = Request["action"];
            slide.Content = Request["content"];
            slide.Discount = Convert.ToInt32(Request["discount"]);
            slide.Image = Request["Anh"];
            slide.updated_at = ViewBag.date;
            UpdateModel(slide);
            db.SubmitChanges();
            return RedirectToAction("Create");

            return this.Edit(id);
        }
        public ActionResult Delete_cre(int id)
        {
            var slide = db.Slides.Where(b => b.ID == id).SingleOrDefault();
            db.Slides.DeleteOnSubmit(slide);
            db.SubmitChanges();
            return RedirectToAction("Create");
        }
    }
}

Laptop/Laptop/Views/slide/Create.cshtml
@{
    ViewBag.Title = "Create";
    Layout = "~/Views/Shared/_Admin.cshtml";
}
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/test/Index">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Form thêm slide</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<div class="card-body pad">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title" style="text-align:center; width:100%">Form thêm slide</h3>
                </div>
                <form method="post" action="/slide/Create">
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                                <tr align="center">
                                    <th>Tiêu đề</th>
                                    <th>Hình ảnh</th>
                                    <th>Nội dung</th>
                                    <th>Hoạt động</th>
                                    <th>Giảm giá</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>

                                <tr class="odd gradeX" align="center">
                                    <td>
                                        <input type="text" class="form-control" placeholder="Điền tiêu đề" name="Ten">
                                    </td>
                                    <td>
                                        <input type="text" class="form-control" placeholder="Điền link ảnh" name="Anh">
                                    </td>
                                    <td>
                                        <input type="text" class="form-control" placeholder="Điền nội dung" name="content">
                                    </td>
                                    <td>
                                        <input type="text" class="form-control" placeholder="Điền hoạt động" name="action">
                                    </td>
                                    <td>
                                        <input type="text" class="form-control" placeholder="Điền giảm giá" name="discount">
                                    </td>
                                    <td>
                                        <button type="submit" class="btn btn-primary">Thêm</button>
                                    </td>
                                </tr>

                            </tbody>
                        </table>
                    </div>
                </form>
                <h3 style="text-align:center; color:red">@ViewBag.test</h3>
            </div>
        </div>
    </div>
    <div class="row">
        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header" style="background-color:sandybrown">
                    <h3 class="card-title" style="text-align:center; width:100%">Thông tin 3 slide được thêm gần nhất</h3>
                </div>
                <div class="card-body">

                    <table id="example2" class="table table-bordered table-hover">
                        <thead>
                            <tr align="center">
                                <th>Tiêu đề</th>
                                <th>Hình ảnh</th>
                                <th>Nội dung</th>
                                <th>Hoạt động</th>
                                <th>Giảm giá</th>
                                <th>Action</th>
                            </tr>
                        </thead>
                        <tbody>
                            @foreach (var item in Model)
                            {
                            <tr class="odd gradeX" align="center">
                                <td>@item.Title</td>
                                <td><img src="@item.Image" width="70" height="70" /></td>
                                <td>@item.Content</td>
                                <td>@item.Action</td>
                                <td>@item.Discount</td>
                                <td>
                                    <i class="fa fa-trash-o" fa-fw></i>@Html.ActionLink("Sửa", "Edit_cre", new { id = item.ID })
                                    <i class="fa fa-pencil fa-fw"></i>@Html.ActionLink("Xóa", "Delete_cre", new { id = item.ID })
                                </td>
                            </tr>
                            }
                        </tbody>
                    </table>
                </div>
            </div>
        </div>
    </div>
</div>

Laptop/Laptop/Views/slide/Edit.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/test/Index">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Form sửa thông tin slide</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<div class="card-body pad">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title" style="text-align:center; width:100%">Form sửa thông tin slide</h3>
                </div>
                <form role="form" method="post" action="/slide/Edit/@Model.ID"
                      enctype="multipart/form-data">
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                                <tr align="center">
                                    <th>ID</th>
                                    <th>Tiêu đề</th>
                                    <th>Hình ảnh</th>
                                    <th>Nội dung</th>
                                    <th>Hoạt động</th>
                                    <th>Giảm giá</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>

                                <tr class="odd gradeX" align="center">
                                    <td>
                                        @Model.ID
                                    </td>
                                    <td>
                                        <input type="text" class="form-control" placeholder="Điền tên slide"
                                            name="Ten" value="@Model.Title">
                                    </td>
                                    <td>
                                        <input type="text" class="form-control" value="@Model.Image" 
                                               placeholder="Điền link ảnh" name="Anh">
                                    </td>
                                    <td>
                                        <input type="text" class="form-control" value="@Model.Content" 
                                               placeholder="Điền nội dung" name="content">
                                    </td>
                                    <td>
                                        <input type="text" class="form-control" value="@Model.Action"
                                               placeholder="Điền hoạt động" name="action">
                                    </td>
                                    <td>
                                        <input type="text" class="form-control" value="@Model.Discount"
                                               placeholder="Điền hoạt động" name="discount">
                                    </td>
                                    <td>
                                        <button type="submit" class="btn btn-primary">Sửa</button>
                                    </td>
                                </tr>

                            </tbody>
                        </table>
                    </div>
                </form>
            </div>
            <!-- /.card -->
        </div>
    </div>
</div>

Laptop/Laptop/Views/slide/Edit_cre.cshtml
@{
    ViewBag.Title = "Edit";
    Layout = "~/Views/Shared/_Admin.cshtml";
}

<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/test/Index">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Form sửa thông tin slide</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>
<div class="card-body pad">
    <div class="row">
        <div class="col-md-12">
            <div class="card card-primary">
                <div class="card-header">
                    <h3 class="card-title" style="text-align:center; width:100%">Form sửa thông tin slide</h3>
                </div>
                <form role="form" method="post" action="/slide/Edit_cre/@Model.ID"
                      enctype="multipart/form-data">
                    <div class="card-body">
                        <table id="example2" class="table table-bordered table-hover">
                            <thead>
                                <tr align="center">
                                    <th>ID</th>
                                    <th>Tiêu đề</th>
                                    <th>Hình ảnh</th>
                                    <th>Nội dung</th>
                                    <th>Hoạt động</th>
                                    <th>Giảm giá</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>

                                <tr class="odd gradeX" align="center">
                                    <td>
                                        @Model.ID
                                    </td>
                                    <td>
                                        <input type="text" class="form-control" placeholder="Điền tên slide"
                                               name="Ten" value="@Model.Title">
                                    </td>
                                    <td>
                                        <input type="text" class="form-control" value="@Model.Image"
                                               placeholder="Điền link ảnh" name="Anh">
                                    </td>
                                    <td>
                                        <input type="text" class="form-control" value="@Model.Content"
                                               placeholder="Điền nội dung" name="content">
                                    </td>
                                    <td>
                                        <input type="text" class="form-control" value="@Model.Action"
                                               placeholder="Điền hoạt động" name="action">
                                    </td>
                                    <td>
                                        <input type="text" class="form-control" value="@Model.Discount"
                                               placeholder="Điền hoạt động" name="discount">
                                    </td>
                                    <td>
                                        <button type="submit" class="btn btn-primary">Sửa</button>
                                    </td>
                                </tr>

                            </tbody>
                        </table>
                    </div>
                </form>
            </div>
            <!-- /.card -->
        </div>
    </div>
</div>

Laptop/Laptop/Views/slide/Index.cshtml
@*@model IPagedList<Laptop.Models.Slide>*@

@*@using PagedList.Mvc;
@using PagedList;*@
@{
    ViewBag.Title = "Index";
    Layout = "~/Views/Shared/_Admin.cshtml";
}
<style>
</style>
<section class="content-header">
    <div class="container-fluid">
        <div class="row mb-2">
            <div class="col-sm-6">
                <h1>Slide</h1>
            </div>
            <div class="col-sm-6">
                <ol class="breadcrumb float-sm-right">
                    <li class="breadcrumb-item"><a href="/test/Index">Trang chủ</a></li>
                    <li class="breadcrumb-item active">Slide</li>
                </ol>
            </div>
        </div>
    </div><!-- /.container-fluid -->
</section>

@*<form class="form-inline ml-3" method="post" action="/slide/Index">
    <div class="container h-100">
        <div class="d-flex justify-content-center h-100">
            <div class="searchbar">
                <input class="search_input" type="text" name="key" placeholder="Nhập tiêu đề">
                <button type="submit" class="btn btn-primary" style="background-color:white; border-color:white; color:blue">
                    <i class="fas fa-search"></i>
                </button>
            </div>
        </div>
    </div>
</form>
<br>*@

<!-- Main content -->
<section class="content">
    <div class="card-body pad">
        <div class="row">
            <div class="col-md-12">
                <div class="card card-primary">
                    <div class="card-header">
                        <h3 class="card-title" style="text-align:center; width:100%">Bảng slide</h3>
                    </div>
                    <!-- /.card-header -->
                    <div class="card-body">
                        <table id="example" class="table table-bordered table-hover">
                            <thead>
                                <tr align="center">
                                    <th>ID</th>
                                    <th>Tiêu đề</th>
                                    <th>Hình ảnh</th>
                                    <th>Nội dung</th>
                                    <th>Hoạt động</th>
                                    <th>Giảm giá</th>
                                    <th>Action</th>
                                </tr>
                            </thead>
                            <tbody>
                                @foreach (var item in ViewBag.slide)
                                {
                                <tr class="odd gradeX" align="center">
                                    <td>@item.ID</td>
                                    <td>@item.Title</td>
                                    <td><img src="@item.Image" width="70" height="70" /></td>
                                    <td>@item.Content</td>
                                    <td>@item.Action</td>
                                    <td>@item.Discount</td>
                                    <td>
                                        <i class="fa fa-trash-o" fa-fw></i>@Html.ActionLink("Sửa", "Edit", new { id = item.ID })
                                        <i class="fa fa-pencil fa-fw"></i>@Html.ActionLink("Xóa", "Delete", new { id = item.ID })
                                    </td>
                                </tr>
                                }
                            </tbody>
                            <tfoot>
                                <tr align="center">
                                    <th>ID</th>
                                    <th>Tiêu đề</th>
                                    <th>Hình ảnh</th>
                                    <th>Nội dung</th>
                                    <th>Hoạt động</th>
                                    <th>Giảm giá</th>
                                    <th>Action</th>
                                </tr>
                            </tfoot>
                        </table>
                        @*<div style="margin-left: 50%;" class="paginate">
                            @Html.PagedListPager(Model, page => Url.Action("Index", "slide", new { page }))
                        </div>*@

                    </div>
                    <!-- /.card-body -->
                </div>
                <!-- /.card -->

            </div>
            <!-- /.col -->
        </div>
        <!-- /.row -->
    </div>
    <!-- /.container-fluid -->
</section>
<!-- /.content -->